### ISSUE TITLE
iqiyi昨天开始报错了

### ISSUE THREAD

**Issue by crossgg** [Sliverkiss/QuantumultX#9]
```
签到失败：{'code': 'A00401', 'message': '用户身份验证失败'}
Traceback (most recent call last):
  File "/ql/data/scripts/raw_Script_iQiYi.py", line 378, in <module>
    iqiyi.main()
  File "/ql/data/scripts/raw_Script_iQiYi.py", line 360, in main
    self.watchVideo()
  File "/ql/data/scripts/raw_Script_iQiYi.py", line 202, in watchVideo
    totalTime = self.get_watch_time()
  File "/ql/data/scripts/raw_Script_iQiYi.py", line 198, in get_watch_time
    watch_time = data['data']['viewtime']['time']
KeyError: 'data'
````
前面都是正常的。

**Comment by Sliverkiss** [comment]
你py的本来我这里反馈什么，找错人了吧
